version: '3'
services:
 mongo :
  image : mongo:latest
  ports:
   - "27017:27017"
  container_name : dockers-mongo
  network_mode: host
  environment :
      MONGO_ROOT_PASSWORD : root
      MONGO_DATABASE : movieDb
      MONGO_USER : root_app
      MONGO_PASSWORD : root123 
 spring:
  image: docker-spring
  build: stackroute/
  restart: always
  network_mode: host
  container_name: springs-app
  depends_on:
   - mongo
   - zuul
   - config-server
   - eureka-server
  ports:
   - 8090:8090
  expose:
   - 8090
 zuul:
  image: docker-zuul
  build: zuulserver/
  restart: always
  network_mode: host
  container_name: zuul-app
  ports:
   - 8081:8081
  expose:
   - 8081
 config-server:
  image: docker-config
  build: configserver/
  restart: always
  container_name: config-app
  network_mode: host
  ports:
   - 8888:8888
  expose:
   - 8888

 eureka-server:
  image: docker-eureka
  build: eureka-server/
  restart: always
  network_mode: host
  container_name: eureka-app
  ports:
   - 8761:8761
  expose:
   - 8761 

   



